favorite_animal = input("What is your favorite animal?\n")
color = input("What is the color of a " + favorite_animal + "?\n")
sound = input("What sound does a " + favorite_animal + " make?\n")           
habitat = input("Where does it live?\n>")
fun_fact = input("What is a fun fact about Lemurs?\n>")
opinion = input("Why do you like them?\n>")
print(" Your favorite animal is a " + favorite_animal + " because " + opinion + ". It is " + color + ", it makes " + sound + ". Their habitat is " + habitat + ". A fun fact about Lemurs is " + fun_fact + ". Cool. " )
